# Generated by Django 5.2.7 on 2025-10-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seasonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.SlugField(max_length=20)),
                ('season_id', models.SlugField(max_length=10)),
                ('league_id', models.SlugField(max_length=10)),
                ('team_id', models.IntegerField()),
                ('team_abbreviation', models.SlugField(max_length=10)),
                ('player_age', models.FloatField(blank=True, null=True)),
                ('gp', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg_pct', models.FloatField()),
                ('fg3m', models.IntegerField()),
                ('fg3a', models.IntegerField()),
                ('fg3_pct', models.FloatField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft_pct', models.FloatField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('pts', models.IntegerField()),
            ],
        ),
    ]
