# Generated by Django 5.2.7 on 2025-10-18 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seasondata',
            unique_together={('player_id', 'season_id', 'team_id')},
        ),
    ]
