# Generated by Django 5.2.7 on 2025-10-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_seasondata_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondata',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='player_nicknames',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
