# Generated by Django 5.2.7 on 2025-10-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_seasondata_player_name_seasondata_player_nicknames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasondata',
            name='ast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='blk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='dreb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fg3_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fg3a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fg3m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fg_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fga',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fgm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='ft_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='fta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='ftm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='gp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='gs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='league_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='oreb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='pf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='player_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='pts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='reb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='season_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='stl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='team_abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='seasondata',
            name='tov',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
