# Generated by Django 5.2.7 on 2025-10-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_seasondata_ast_alter_seasondata_blk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondata',
            name='awards',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
