# Generated by Django 5.2.7 on 2025-10-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_seasondata_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondata',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
    ]
