# Generated by Django 5.2.7 on 2025-10-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_seasondata_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasondata',
            name='country',
            field=models.CharField(default='USA', max_length=100, null=True),
        ),
    ]
