# Generated by Django 5.2.7 on 2025-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_seasondata_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondata',
            name='bday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='draft_pick',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='draft_round',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='draft_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seasondata',
            name='weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
