# Generated by Django 5.2.7 on 2025-11-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_seasondata_bday_seasondata_draft_pick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='awardsBySeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
