# Generated by Django 5.2.7 on 2025-11-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_awardsbyseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayoffSeasonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('season_id', models.CharField(max_length=10)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('team_id', models.IntegerField()),
                ('league_id', models.CharField(blank=True, max_length=10, null=True)),
                ('team_abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('player_age', models.FloatField(blank=True, null=True)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('gs', models.IntegerField(blank=True, null=True)),
                ('minutes', models.FloatField(blank=True, null=True)),
                ('fgm', models.FloatField(blank=True, null=True)),
                ('fga', models.FloatField(blank=True, null=True)),
                ('fg_pct', models.FloatField(blank=True, null=True)),
                ('fg3m', models.FloatField(blank=True, null=True)),
                ('fg3a', models.FloatField(blank=True, null=True)),
                ('fg3_pct', models.FloatField(blank=True, null=True)),
                ('ftm', models.FloatField(blank=True, null=True)),
                ('fta', models.FloatField(blank=True, null=True)),
                ('ft_pct', models.FloatField(blank=True, null=True)),
                ('oreb', models.FloatField(blank=True, null=True)),
                ('dreb', models.FloatField(blank=True, null=True)),
                ('reb', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('stl', models.FloatField(blank=True, null=True)),
                ('blk', models.FloatField(blank=True, null=True)),
                ('tov', models.FloatField(blank=True, null=True)),
                ('pf', models.FloatField(blank=True, null=True)),
                ('pts', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('player_id', 'season_id', 'team_id')},
            },
        ),
    ]
